name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Heroku CONTAINER
        run: heroku container:login

      - name: Push Docker image to Heroku
        run: heroku container:push web --app telconix

      - name: Release Docker image on Heroku
        run: heroku container:release web --app telconix
