name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "telconix"
        run: |
          heroku container:login
          heroku container:push web -a $(appname)
          heroku container:release web -a $(appname)
